---
server:
  port: 9292

management:
  server:
    port: 9292

spring:
  application:
    environment: dev

issuer-ui:
  issuer-server:
    base-url: http://issuer-server:9240

#maskinporten:
#  oauth2:
#    issuer: https://maskinporten.dev/
