---
server:
  port: 8080
  servlet:
    context-path: /

spring:
  thread-executor: virtual
  application:
    name: digital-lommebok-issuer-ui
    environment: default


# Spring Boot Actuator
management:
  server:
    port: 8090
  endpoints:
    web:
      exposure:
        include: info,version,prometheus,health
      base-path: /
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
      environment: ${spring.application.environment}

issuer-ui:
  issuer-server:
    issuance-endpoint: /api/v1/credential-offer/create

# Digdir standard logging
digdir:
  access:
    logging:
      filtering:
        static-resources: true

