---
server:
  port: 9292

management:
  server:
    port: 9292

spring:
  application:
    environment: docker

issuer-ui:
  issuer-server:
#    base-url: http://issuer-server:9240
    base-url: https://utsteder.eidas2sandkasse.dev
