---
spring:
  application:
    environment: test

issuer-ui:
  issuer-server:
    base-url: https://utsteder.test.eidas2sandkasse.net

#maskinporten:
#  oauth2:
#    issuer: https://test.maskinporten.no/
